### ISSUE TITLE
jumphosts: manage ssh keys for the jump users

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-vpc#8]

**Comment by gozer** [comment]
Various bits:
 - *confd* from Consul, generates a puppet manifest
  - including required deletions
 - *puppet* to manage users / install ssh keys
 - Hax0r: *ldap* => *Consul*

**Comment by gozer** [comment]
:clock1: 8h + 4h = 12h

**Comment by danparsons** [comment]
I'm working on the ldap => Consul part of this, and I started digging through what we have in the kv store right now. My goal is to come up with a layout for storing ssh keys that makes sense with how we store other pieces of data. I see something that looks like ssh keys in there already, but it's weird. For example, there's a key "environments/sandbox/global/sshkey/fredbob/sshkey_1", but its value is only 8 characters long, obviously not a valid ssh key. There are a few other sshkey keys as well, and they're all truncated.

Questions:
(1) What's going on here? What are these things?

(2) Should I use this same layout? (basically, storing keys in environments/sandbox/global/sshkey/username/sshkey_N)

**Comment by tinnightcap** [comment]
You should store your keys in an area specific to the application you are working on. I guess the application in this case would be jumphost. So it would be something like environments/sandbox/jumphost/whatever/whatever. you need to put it in environments, then in the environment you are in (in other words parameterize that part) sandbox|stage|prod. After that you can pretty much do what you want with the layout, I would recommend putting anything you do in a directory of its own in case other things wind up in consul for the jumphosts. So something like environments/sandbox/jumphost/ssh_keys/mykey.

Feel free to ping me on IRC if this does not make sense.

**Comment by danparsons** [comment]
Initial commit is here: https://github.com/danparsons/nubis-jumphost/blob/master/nubis/bin/ldap2consul.py

So far it gets all the ssh keys (and unix usernames) for everyone in a specific group in Mozilla's LDAP, as specified in ldap2consul.conf. Next step is writing that to consul, which won't take much longer.

**Comment by danparsons** [comment]
Per conversation with jd & gozer, there are some changes to this issue, specifically that coming soon there will be a need to support arbitrary ssh keys being loaded into arbitrary servers. The plan for this issue is to still focus on just jumphosts, but I'm going to engineer things with this future arbitraryness in mind.

Specifically, I'm going to use a global namespace for all ssh keys, and then on the individual server level, a username will simply be referenced, as opposed to storing the same ssh key in multiple places. 

This change will lengthen the completion time of this issue a little bit, but it will save much more time later on when this tool needs to be extended.

**Comment by danparsons** [comment]
ldap2consul.py is now complete (one missing nice to have is the ability to delete users that no longer exist, will add that later). It supports multiple ssh keys, too. You can see the data it's loaded into consul here: 

http://ui.us-west-2.consul.sandbox.nubis.allizom.org/ui/#/us-west-2/kv/environments/sandbox/global/ldap/

Latest version is in same location:

https://github.com/danparsons/nubis-jumphost/blob/master/nubis/bin/ldap2consul.py

**Comment by danparsons** [comment]
consul2unixusers.py is now complete. You can see it here:

https://github.com/danparsons/nubis-jumphost/blob/master/nubis/bin/consul2unixusers.py

If you want to see a system I've run consul2unixusers.py on, check out 10.166.9.184, aka dpaste-lerxst. All users and ssh keys there were created by this script.

Remaining work:

(1) Updating nubis-jumphost to include consul2unix.py and its dependencies
(2) Finding a home for ldap2consul.py and getting it running every 5 minutes or whatever
(3) Need to edit /etc/sudoers in all Nubis base images to specify NOPASSWD for the 'sudo' group - as it is right now, people cannot get root access because I am not syncing shadow passwords (and have no intention of doing so)

**Comment by danparsons** [comment]
Just to clarify how this system works, as I realize it may not be obvious to some people:

(1) ldap2consul.py pulls attributes out of LDAP for employees matching a given LDAP group (specified in ldap2consul.conf) and writes that data to Consul. This will be run in cron somewhere, probably in scl3, maybe the admin host.

(2) consul2unixusers.py reads data from Consul and calls 'useradd' where users do not exist, and writes lines to authorized_keys for keys that do not exist for a given user. This will be run in cron on every nubis machine eventually.

**Comment by gozer** [comment]
General comments on consul2unixusers.py, staying at a high level.

- general usability concerns with the config file approach. Would be nice if all or most configuration file options could also be supplied on the command-line.
- Error checking and diagnostic information should be increased to production level
- Absence of tests
- Processing each entry at a time instead of in bulk
- Groups are the basic search criteria, so I would hide the LDAP specific filters away in some special power-user option, and add support for something like a 'groups' options for group names to search for
- Group membership is not exposed in consul, so the consumer of this has no way of selecting the users it wants short of *all* or specific known user's CNs
- This should inspect Consul's state, instead of just writing the entire LDAP information over again (side-effect of this is not deleting users or keys)

The last issue is the 'sudo' group and related work, I am not sure I understand why it's needed.

General comments on consul2unixusers.py, staying at a high level:

- general usability concerns with the config file approach. Would be nice if all or most configuration file options could also be supplied on the command-line.
- Error checking and diagnostic information should be increased to production level
- Absence of tests
- Processing each entry at a time instead of in bulk
- Group support:
  - Group(s) to pick from Consul
  - Local group to put them into
- Data validation. Consul is safe to consider secure, but one should not assume external data ever is
- Using puppet to drive the user management instead of handling directly with the script

About the remaining work, looking good (I'd file separate issues to track):
- [ ] Updating nubis-jumphost to include consul2unix.py and its dependencies
- [ ] Finding a home for ldap2consul.py and getting it running every 5 minutes or whatever
